apiVersion: v1
kind: Service
metadata:
  name: postgres-external
  labels:
    app: postgres-db
spec:
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: postgres-db
  type: LoadBalancer
