apiVersion: v1
kind: Service
metadata:
  name: web-server-service
  labels:
    app: web-server
spec:
  selector:
    app: web-server
  ports:
  - name: frontend
    port: 80
    targetPort: 3000
  - name: backend
    port: 3001
    targetPort: 3001
  type: LoadBalancer
